### ISSUE TITLE
SublimeREPL integration fails

### ISSUE THREAD

**Issue by rtfeldman** [dnalot/elm-sublime#1]
Console output on startup:

```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/rtfeldman/Library/Application Support/Sublime Text 3/Packages
state path: /Users/rtfeldman/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.548131
first paint time: 0.627591
startup time: 0.760959
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Alignment.Alignment
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin elm-sublime.elm_generate
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "elm_generate in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 43
    print 'Wrote {}'.format(path.format(name(v) + '.sublime-snippet'))
                   ^
SyntaxError: invalid syntax
reloading plugin elm-sublime.elm_make
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "elm_make in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 19, in <module>
AttributeError: 'module' object has no attribute 'ExecCommand'
reloading plugin elm-sublime.elm_open_in_browser
reloading plugin elm-sublime.elm_project
reloading plugin elm-sublime.elm_show_type
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "elm_show_type in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 330, in <module>
  File "elm_show_type in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 77, in load_docs
FileNotFoundError: [Errno 2] No such file or directory: 'docs.json'
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin Highlight Build Errors.HighlightBuildErrors
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Ruby Markers.ruby_markers
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SmartMarkdown.headline
reloading plugin SmartMarkdown.headline_level
reloading plugin SmartMarkdown.headline_move
reloading plugin SmartMarkdown.pandoc_render
reloading plugin SmartMarkdown.smart_folding
reloading plugin SmartMarkdown.smart_list
reloading plugin SmartMarkdown.smart_table
reloading plugin SmartMarkdown.table
reloading plugin SmartMarkdown.utilities
reloading plugin VAlign.valign
reloading plugin Vintageous.__init__
reloading plugin Vintageous.dev_cmds
reloading plugin Vintageous.ex_commands
reloading plugin Vintageous.ex_main
reloading plugin Vintageous.ex_motions
reloading plugin Vintageous.jump_list_cmds
reloading plugin Vintageous.modelines
reloading plugin Vintageous.state
reloading plugin Vintageous.test_runner
reloading plugin Vintageous.xactions
reloading plugin Vintageous.xmotions
reloading plugin Vintageous.xsupport
reloading plugin Vintageous.xsupport_mouse
reloading plugin Vintageous.builder
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Vintageous.builder'
reloading plugin Vintageous.toplist
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Vintageous.toplist'
reloading plugin MacTerminal.open_mac_terminal
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-08-03 20:43:17, next run at 2015-08-03 21:43:17 or after
```

**Comment by dnalot** [comment]
```
  File "elm_generate in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 43
    print 'Wrote {}'.format(path.format(name(v) + '.sublime-snippet'))
                   ^
SyntaxError: invalid syntax
```
Compatibility issue with existing code. Easy fix.
```
  File "elm_make in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 19, in <module>
AttributeError: 'module' object has no attribute 'ExecCommand'
```
Maybe I'm trying to import `Highlight Build Errors` before it's loaded. Looking into that.
```
  File "elm_show_type in /Users/rtfeldman/Library/Application Support/Sublime Text 3/Installed Packages/elm-sublime.sublime-package", line 77, in load_docs
FileNotFoundError: [Errno 2] No such file or directory: 'docs.json'
```
Don't know why but unrelated to REPL and fits in the category of fixed by Elm Oracle. In fact REPL loads last. I wonder if that has something to do with it. Thanks!

**Comment by dnalot** [comment]
So I forgot to rebase the `real` branch. Easy fix. Your log led me to an architectural change to lazily load all dependencies though. The final issue should be resolved by generalizing my parser.
